name: Test Installation
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10']
    name: Test Build ${{ matrix.os }}, Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            export PYTHONPATH=$PYTHONPATH:test/
          elif [ ${{ matrix.os }} == 'windows-latest' ]; then
            set PYTHONPATH=%PYTHONPATH%;test\
          fi
      - name: Test
        run: |
          python -m unittest discover