name: Build and Deploy Docs
on: [push, pull_request, workflow_dispatch]

permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          pip install .
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy docs to gh pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}